### PR TITLE
Xschemrc update

### PR DESCRIPTION
**Pull request by mole99**
Updates the xschemrc of the superproject and its dependencies to follow the best practice of:

1. Source the PDK xschemrc file, if it hasn't been sourced yet.
2. Add the current directory to the XSCHEM_LIBRARY_PATH.
3. Source the xschemrc file of any of the dependencies.

This is repeated recursively once the xschemrc of the superproject is sourced.

### CODE REVIEW

**Review by RTimothyEdwards — APPROVED** [review]
This is fine, although this entire repository has become effectively deprecated by the last change to the POR.  The change removed the bandgap voltage from the POR input and made the POR entirely self-contained, so the operation no longer depends on multiple blocks and does not need to be simulated as such.

**Comment by mole99** [comment]
That's good to know :)
I made the changes because Eric reported an issue with the symbols in one of the dependencies. The reason was that this repository and some of the submodules were still copying the PDKs xschemrc into the repository, this is now done properly.

**Review by RTimothyEdwards — COMMENTED** [review]
The repository name of sky130_sw_ip__bgrref_por has been changed to sky130_sw_ip__por, but the subdirectory still has the old name, which is probably fine but seems a bit odd.

**Comment by mole99** [comment]
I changed the path to `dependencies/sky130_sw_ip__por`, but couldn't quickly figure out how to change the reference in `.gitmodules` without manual editing, so I left it at that. One could just remove and re-add the submodule though.

**Pull request merged**
